[workspace]
resolver = "2"
members = ["task_1_create_account", "task_2_transfer", "task_3_create_and_transfer"]

[workspace.dependencies]
solana-sdk = "1.18.14"
solana-client = "1.18.14"
anyhow = "1.0.86"
